#!/bin/bash
# Clone the Flutter stable branch with depth 1 for speed
if [ ! -d "flutter" ]; then
  echo "Cloning Flutter SDK..."
  git clone https://github.com/flutter/flutter.git -b stable --depth 1
fi

# Add Flutter to PATH
export PATH="$PATH:$(pwd)/flutter/bin"

# Disable analytics for cleaner logs
flutter config --no-analytics

# Enable Web support
flutter config --enable-web

# Generate supabase_config.dart if it doesn't exist (e.g. on Vercel)
CONFIG_PATH="lib/core/constants/supabase_config.dart"
if [ ! -f "$CONFIG_PATH" ]; then
  echo "Generating supabase_config.dart..."
  mkdir -p lib/core/constants
  
  # Fallback to current config values if env vars are not set
  URL=${SUPABASE_URL:-"https://axfwupyfcthaolstuqip.supabase.co"}
  ANON_KEY=${SUPABASE_ANON_KEY:-"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4Znd1cHlmY3RoYW9sc3R1cWlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA1NjIxMDgsImV4cCI6MjA5NjEzODEwOH0.j0WwNA_ipraGL3Ha2BLilydI0pLJWjGk5Z1of0jvecg"}

  cat <<EOT > "$CONFIG_PATH"
/// Supabase Configuration (Auto-generated by vercel-build.sh)
class SupabaseConfig {
  SupabaseConfig._();

  static const String url = '$URL';
  static const String anonKey = '$ANON_KEY';
}
EOT
  echo "Generated config file successfully."
fi

# Build Web in release mode
echo "Building Flutter Web..."
flutter build web --release

